import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

interface ReportData {
  playerName: string;
  playerAge: number;
  finalNetworth: number;
  cagr: number;
  profitLoss: number;
  reportContent: string;
  generatedDate: string;
  reportId?: string;
}

/**
 * Generate PDF by capturing the UI exactly as shown.
 * - Single page if content fits
 * - Multiple pages only when required
 * - No white background or blank pages
 */
export async function generateHTMLReportPDF(
  contentElement: HTMLElement,
  data: ReportData
): Promise<void> {
  try {
    const originalCursor = document.body.style.cursor;
    document.body.style.cursor = 'wait';

    /* --------------------------------------------------
       1. Create offscreen container
    -------------------------------------------------- */
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.top = '0';
    container.style.width = '210mm';
    container.style.backgroundColor = '#1a1a2e';
    container.style.fontFamily = 'Arial, sans-serif';
    container.style.padding = '40px';
    container.style.boxSizing = 'border-box';
    document.body.appendChild(container);

    /* --------------------------------------------------
       2. Header
    -------------------------------------------------- */
    container.innerHTML = `
      <h1 style="color:#4ecca3;font-size:32px;border-bottom:3px solid #4ecca3;padding-bottom:15px;">
        AI Trading Performance Report
      </h1>

      <div style="background:rgba(78,204,163,0.1);padding:20px;border-radius:12px;border-left:4px solid #4ecca3;">
        <p style="color:#e0e0e0"><strong>Player:</strong> ${data.playerName} (Age: ${data.playerAge})</p>
        <p style="color:#e0e0e0"><strong>Report ID:</strong> ${data.reportId || 'N/A'}</p>
        <p style="color:#e0e0e0"><strong>Generated:</strong> ${data.generatedDate}</p>
      </div>

      <div style="display:flex;gap:15px;margin-top:20px;">
        <div style="flex:1;background:rgba(52,211,153,.15);padding:18px;border-radius:10px;border:2px solid #34d399;">
          <div style="color:#34d399;font-size:12px;">FINAL NETWORTH</div>
          <div style="color:#fff;font-size:22px;font-weight:bold;">
            ₹${data.finalNetworth.toLocaleString('en-IN')}
          </div>
        </div>

        <div style="flex:1;background:rgba(59,130,246,.15);padding:18px;border-radius:10px;border:2px solid #3b82f6;">
          <div style="color:#3b82f6;font-size:12px;">CAGR</div>
          <div style="color:#fff;font-size:22px;font-weight:bold;">
            ${data.cagr.toFixed(2)}%
          </div>
        </div>

        <div style="flex:1;background:rgba(${data.profitLoss >= 0 ? '34,197,94' : '239,68,68'},.15);
                    padding:18px;border-radius:10px;border:2px solid ${data.profitLoss >= 0 ? '#22c55e' : '#ef4444'};">
          <div style="color:${data.profitLoss >= 0 ? '#22c55e' : '#ef4444'};font-size:12px;">
            PROFIT / LOSS
          </div>
          <div style="color:#fff;font-size:22px;font-weight:bold;">
            ${data.profitLoss >= 0 ? '+' : ''}₹${Math.abs(data.profitLoss).toLocaleString('en-IN')}
          </div>
        </div>
      </div>
    `;

    /* --------------------------------------------------
       3. Clone report content
    -------------------------------------------------- */
    const contentClone = contentElement.cloneNode(true) as HTMLElement;
    // Remove any enforced minHeight/padding to avoid creating extra long containers (helps single-page PDFs)
    contentClone.style.backgroundColor = '#1a1a2e';
    contentClone.style.color = '#e0e0e0';
    contentClone.style.minHeight = '';
    contentClone.style.paddingBottom = '0';
    contentClone.style.boxSizing = 'border-box';
    container.appendChild(contentClone);

    /* --------------------------------------------------
       4. Footer
    -------------------------------------------------- */
    const footer = document.createElement('div');
    footer.style.marginTop = '40px';
    footer.style.borderTop = '2px solid #4ecca3';
    footer.style.paddingTop = '20px';
    footer.style.textAlign = 'center';
    footer.innerHTML = `
      <p style="color:#4ecca3;font-weight:bold;">Generated by BullRun Game</p>
      <p style="color:#6b7280;font-size:12px;">AI-Powered Trading Performance Analysis</p>
    `;
    container.appendChild(footer);

    await new Promise(res => setTimeout(res, 300));

    /* --------------------------------------------------
       5. Capture canvas
    -------------------------------------------------- */
    const canvas = await html2canvas(container, {
      scale: 2,
      backgroundColor: '#1a1a2e',
      useCORS: true,
      logging: false,
      windowWidth: container.scrollWidth,
      windowHeight: container.scrollHeight,
    });

    document.body.removeChild(container);

    /* --------------------------------------------------
       6. Create PDF
    -------------------------------------------------- */
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgData = canvas.toDataURL('image/png');

    const pageWidth = 210;
    const pageHeight = 297;
    const imgHeight = (canvas.height * pageWidth) / canvas.width;

    const paintBackground = () => {
      pdf.setFillColor(26, 26, 46);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');
    };

    paintBackground();
    pdf.addImage(imgData, 'PNG', 0, 0, pageWidth, imgHeight);

    /* --------------------------------------------------
       7. Add extra pages ONLY if needed
    -------------------------------------------------- */
    if (imgHeight > pageHeight + 8) { // allow small tolerance to avoid tiny extra page
      let heightLeft = imgHeight - pageHeight;
      let position = -pageHeight;

      // Continue adding pages while there's meaningful content remaining (> 8mm)
      while (heightLeft > 8) {
        pdf.addPage();
        paintBackground();
        pdf.addImage(imgData, 'PNG', 0, position, pageWidth, imgHeight);
        heightLeft -= pageHeight;
        position -= pageHeight;
      }
    }

    /* --------------------------------------------------
       8. Save
    -------------------------------------------------- */
    document.body.style.cursor = originalCursor;

    const filename = `TradingReport_${data.playerName.replace(/\s+/g, '_')}_${new Date()
      .toISOString()
      .split('T')[0]}.pdf`;

    pdf.save(filename);
  } catch (err) {
    document.body.style.cursor = 'default';
    throw err;
  }
}
