import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

interface ReportData {
  playerName: string;
  playerAge: number;
  finalNetworth: number;
  cagr: number;
  profitLoss: number;
  reportContent: string;
  generatedDate: string;
  reportId?: string;
}

/**
 * Generate PDF by capturing the beautiful UI as an image
 * This preserves all colors, formatting, and styling exactly as shown
 */
export async function generateHTMLReportPDF(
  contentElement: HTMLElement,
  data: ReportData
): Promise<void> {
  try {
    // Show loading indicator
    const originalCursor = document.body.style.cursor;
    document.body.style.cursor = 'wait';

    // Create a temporary container for rendering
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.top = '0';
    container.style.width = '210mm'; // A4 width
    container.style.backgroundColor = '#1a1a2e';
    container.style.fontFamily = 'Arial, sans-serif';
    container.style.padding = '40px';
    container.style.boxSizing = 'border-box';
    document.body.appendChild(container);

    // Create header with player info and metrics
    const headerHTML = `
      <div style="margin-bottom: 0px;">
        <h1 style="color: #4ecca3; font-size: 32px; margin-bottom: 0px; font-family: Arial, sans-serif; border-bottom: 3px solid #4ecca3; padding-bottom: 15px;">
          AI Trading Performance Report
        </h1>
        <div style="background: rgba(78, 204, 163, 0.1); padding: 20px; border-radius: 12px; border-left: 4px solid #4ecca3; margin-bottom: 0px;">
          <p style="color: #e0e0e0; margin: 8px 0; font-size: 16px; font-family: Arial, sans-serif;">
            <strong style="color: #4ecca3;">Player:</strong> ${data.playerName} (Age: ${data.playerAge})
          </p>
          <p style="color: #e0e0e0; margin: 8px 0; font-size: 16px; font-family: Arial, sans-serif;">
            <strong style="color: #4ecca3;">Report ID:</strong> ${data.reportId || 'N/A'}
          </p>
          <p style="color: #e0e0e0; margin: 8px 0; font-size: 16px; font-family: Arial, sans-serif;">
            <strong style="color: #4ecca3;">Generated:</strong> ${data.generatedDate}
          </p>
        </div>
        <div style="display: flex; gap: 15px; margin-bottom: 0px;">
          <div style="flex: 1; background: rgba(52, 211, 153, 0.15); padding: 18px; border-radius: 10px; border: 2px solid #34d399;">
            <div style="color: #34d399; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 0px;">Final Networth</div>
            <div style="color: #ffffff; font-size: 22px; font-weight: bold;">₹${data.finalNetworth.toLocaleString('en-IN')}</div>
          </div>
          <div style="flex: 1; background: rgba(59, 130, 246, 0.15); padding: 18px; border-radius: 10px; border: 2px solid #3b82f6;">
            <div style="color: #3b82f6; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 0px;">CAGR</div>
            <div style="color: #ffffff; font-size: 22px; font-weight: bold;">${data.cagr.toFixed(2)}%</div>
          </div>
          <div style="flex: 1; background: rgba(${data.profitLoss >= 0 ? '34, 197, 94' : '239, 68, 68'}, 0.15); padding: 18px; border-radius: 10px; border: 2px solid ${data.profitLoss >= 0 ? '#22c55e' : '#ef4444'};">
            <div style="color: ${data.profitLoss >= 0 ? '#22c55e' : '#ef4444'}; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 0px;">Profit/Loss</div>
            <div style="color: #ffffff; font-size: 22px; font-weight: bold;">${data.profitLoss >= 0 ? '+' : ''}₹${Math.abs(data.profitLoss).toLocaleString('en-IN')}</div>
          </div>
        </div>
      </div>
    `;

    container.innerHTML = headerHTML;

    // Clone and add the actual report content
    const contentClone = contentElement.cloneNode(true) as HTMLElement;
    contentClone.style.color = '#e0e0e0';
    container.appendChild(contentClone);

    // Add footer
    const footer = document.createElement('div');
    footer.style.marginTop = '40px';
    footer.style.borderTop = '2px solid #4ecca3';
    footer.style.paddingTop = '20px';
    footer.style.textAlign = 'center';
    footer.innerHTML = `
      <p style="color: #4ecca3; font-size: 14px; font-weight: bold; margin-bottom: 0px;">Generated by BullRun Game</p>
      <p style="color: #6b7280; font-size: 12px;">AI-Powered Trading Performance Analysis</p>
    `;
    container.appendChild(footer);

    // Wait for rendering
    await new Promise(resolve => setTimeout(resolve, 500));

    // Capture as canvas
    const canvas = await html2canvas(container, {
      scale: 2,
      backgroundColor: '#1a1a2e',
      logging: false,
      useCORS: true,
      allowTaint: true,
      windowWidth: container.scrollWidth,
      windowHeight: container.scrollHeight,
    });

    // Remove temporary container
    document.body.removeChild(container);

    // Create PDF
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const imgData = canvas.toDataURL('image/png');
    const imgWidth = 210; // A4 width in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 0;
    let page = 1;

    // Add first page
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= 297;

    // Add additional pages if content overflows
    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= 297;
      page++;
    }

    // Restore cursor
    document.body.style.cursor = originalCursor;

    // Generate filename and save
    const filename = `TradingReport_${data.playerName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(filename);

    console.log(`PDF generated successfully with ${page} page(s)!`);
  } catch (error) {
    console.error('Error generating PDF:', error);
    document.body.style.cursor = 'default';
    throw error;
  }
}
